version: '3.9'
services:
  cache:
    image: redis:alpine
    restart: on-failure
    ports:
      - '6380:6379'
    volumes:
      - cache:/data

  db:
    image: postgres:latest
    volumes:
      - db:/var/lib/postrgresql/data/
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: example-pg-docker

  app:
    build:
      context: .
    depends_on:
      - db
      - cache
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - .:/workspace

volumes:
  db: {}
  cache: {}
