version: '3.9'
services:
  cache:
    container_name: backend_cache
    image: redis:6.2.5-alpine
    command: redis-server --appendonly yes
    volumes:
      - cache_data:/var/lib/redis/data
    ports:
      - '6379:6379'

  db:
    container_name: backend_db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postrgresql/data/
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg_pass
      - POSTGRES_DB=backend
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_ARGS: "--no-root"
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./app:/app/app/:cached
      - ./alembic:/app/alembic/:cached
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - 'POSTGRES_SERVER=db'
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@star.lite
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  postgres_data:
  cache_data:
