[tool.poetry]
name = "starlite-example-api"
version = "0.1.0"
description = "An containerized example backend stack using starlite and postgres"
authors = ["yudjinn <yudjinncoding@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
alembic = "*"
asyncpg = "*"
passlib = {extras = ["bcrypt"], version = "*"}
psycopg2 = "*"
python-dotenv = "*"
sqlalchemy = "*"
starlite = "*"
uvicorn = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-dotenv = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pylint.MESSAGE_CONTROL]
disable = [
    "fixme",
    "missing-module-docstring",
    "missing-class-docstring",
    "line-too-long",
    "missing-function-docstring",
    "no-self-use",
    "not-async-context-manager",
    "no-self-argument",
    "too-few-public-methods",
    "no-member"
]
enable = "useless-suppression"

[tool.pylint.REPORTS]
msg-template = "{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}"
reports = "no"

[tool.pylint.FORMAT]
max-line-length = "120"

[tool.pylint.VARIABLES]
ignored-argument-names = "args|kwargs|_|__"

[tool.pylint.BASIC]
good-names = "_,i,e,v,T"

[tool.coverage.run]
omit = ["*/tests/*"]
