[tool.poetry]
name = "backend"
version = "0.1.0"
description = "An containerized example backend stack using starlite and postgres"
authors = ["yudjinn <yudjinncoding@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
alembic = "*"
starlite = "*"
uvicorn = "*"
passlib = {extras = ["bcrypt"], version = "*"}
python-dotenv = "*"
psycopg2 = "*"

[tool.poetry.dev-dependencies]
black = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
