[tool.poetry]
name = "backend"
version = "0.1.0"
description = "An example backend stack using starlite and postgres"
authors = ["yudjinn <yudjinncoding@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
alembic = "^1.7.5"
ormar = {extras = ["postgresql"], version = "^0.10.23"}
starlite = "^0.1.3"
uvicorn = "^0.16.0"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-dotenv = "^0.19.2"

[tool.poetry.dev-dependencies]
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
